### ISSUE TITLE
Disparo de email

### ISSUE THREAD

**Issue by lagolucas** [projeto7c0/projeto7c0.github.io#1]
A funcionalidade "Fale conosco" não dispara e-mails, precisa ser implementada.

**Comment by bertassi** [comment]
Static HTML contact form functionality integrated to Formspree (check [Formspree Setup](https://formspree.io/#setup) for more details). It is necessary to validate the account. Field validation is being done with javascript.

**Comment by bertassi** [comment]
For the next release, I recommend [Basin](https://usebasin.com/) as another way of implementing this functionality. Let's keep it on the radar.
